language: c
sudo: false

addons:
  apt:
    packages:
    - libgmp-dev

cache:
  directories:
  - $HOME/.stack

# Use this kind of code to execute tests for each subpart of workflow
# matrix:
#   include:
#   - env: 
#       - RESOLVER_FLAG="--stack-yaml lts-8.yaml"
#       - BUILD_PKGS=""
#       - TEST_PKGS=""
#     addons: {apt: {packages: [libgmp-dev]}}

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack

install:
  - stack +RTS -N2 -RTS setup
  - stack +RTS -N2 -RTS build --only-snapshot
  - stack +RTS -N2 -RTS install hindent
  - stack +RTS -N2 -RTS install cabal-install

script:
  - git --version
  - stack --version
  - ./zift.hs run
