flags: {}
packages:
- workflow
extra-deps:
- introduction-0.0.1.0
- optparse-applicative-0.13.2.0
- orgmode-parse-0.1.1.3
- validity-containers-0.1.0.3
- validity-0.3.3.0
- validity-path-0.1.0.1
- text-time-0.2.0
- dates-0.2.2.1
- mustache-2.2.3
- aeson-1.2.0.0
- genvalidity-hspec-0.4.0.0
- genvalidity-0.3.2.0
- genvalidity-property-0.0.0.0
- genvalidity-time-0.0.0.2
- validity-time-0.0.0.1
resolver: lts-8.11
