* Getting my tax back after the internship
** CANCELLED for a response from peeps
   CLOSED: [2016-09-15 Thu 13:32]
   - State "CANCELLED"  from "WAITING"    [2016-09-15 Thu 13:32]
If they don't respond, we'll have to take some action ourselves

No response to peeps
** DONE for a response from Raj
   CLOSED: [2016-09-16 Fri 16:18]
   - State "DONE"       from "WAITING"    [2016-09-16 Fri 16:18]
Raj told me to forward the email to her.
I did that, now waiting for her to tell me what to do.
I do have some more info:

Will get a P60 in April/May
will get a P45 after the internship

need to apply for tax returns myself through HMRC

Need to set up a HMRC account online but need access to 2fac before I can do that.
** DONE read the email from peeps
   CLOSED: [2016-09-16 Fri 19:29]
Payroll have to calculate & deduct taxes according to the Tax Code issued by the HMRC and detailed on your payslip. Once a P45 is issued after your final payroll has been processed then any overpayment of taxes can be claimed back directly through the HMRC and will not happen automatically through payroll.

Please see the below link from the HMRC website regarding tax refunds:
https://www.gov.uk/claim-tax-refund/too-much-tax-taken-from-your-pay

** DONE Set up a HMRC account online                                   :home:
   CLOSED: [2016-09-16 Fri 19:50]

All that's left to do is set up 2fac

HMRC:

User id: 795914395806
Password: GovP0912      
** DONE for my P45
   CLOSED: [2016-10-26 Wed 17:57]
** DONE Email my recruiter to ask for my P45
   CLOSED: [2016-10-26 Wed 17:57]
** DONE for a response from the recruiter
   CLOSED: [2016-10-28 Fri 10:33]
** DONE look here again
   CLOSED: [2016-10-28 Fri 10:45]
https://www.gov.uk/claim-tax-refund/youve-stopped-work
** DONE send the form
   CLOSED: [2016-10-28 Fri 11:46]
Pay As You Earn
HM Revenue and Customs
BX9 1AS
United kingdom
** WAITING for my tax back
